package defaults

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

type DefaultsManager struct {
	outputDir string
}

type DefaultsDomain struct {
	Domain string                 `json:"domain"`
	Values map[string]interface{} `json:"values"`
}

func NewDefaultsManager(outputDir string) *DefaultsManager {
	return &DefaultsManager{
		outputDir: outputDir,
	}
}

func (d *DefaultsManager) ImportantDomains() []string {
	return []string{

		"com.apple.dock",

		"com.apple.finder",

		"NSGlobalDomain",

		"com.apple.HIToolbox",

		"com.apple.AppleMultitouchTrackpad",
		"com.apple.driver.AppleBluetoothMultitouch.trackpad",

		"com.apple.screencapture",

		"com.apple.Safari",

		"com.apple.menuextra.clock",
		"com.apple.systemuiserver",

		"com.apple.spaces",

		"com.apple.TextEdit",

		"com.apple.Terminal",

		"com.apple.ActivityMonitor",

		"com.apple.TimeMachine",
	}
}

func (d *DefaultsManager) BackupAll() error {
	if err := os.MkdirAll(d.outputDir, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	domains := d.ImportantDomains()
	var allDomains []DefaultsDomain

	for _, domain := range domains {
		values, err := d.readDomain(domain)
		if err != nil {

			continue
		}

		if len(values) > 0 {
			allDomains = append(allDomains, DefaultsDomain{
				Domain: domain,
				Values: values,
			})
		}
	}

	outputFile := filepath.Join(d.outputDir, "macos-defaults.json")
	data, err := json.MarshalIndent(allDomains, "", "  ")
	if err != nil {
		return fmt.Errorf("failed to marshal defaults: %w", err)
	}

	if err := os.WriteFile(outputFile, data, 0644); err != nil {
		return fmt.Errorf("failed to write defaults file: %w", err)
	}

	scriptFile := filepath.Join(d.outputDir, "restore-defaults.sh")
	script := d.generateRestoreScript(allDomains)
	if err := os.WriteFile(scriptFile, []byte(script), 0755); err != nil {
		return fmt.Errorf("failed to write restore script: %w", err)
	}

	return nil
}

func (d *DefaultsManager) readDomain(domain string) (map[string]interface{}, error) {
	cmd := exec.Command("defaults", "read", domain)
	var out bytes.Buffer
	var stderr bytes.Buffer
	cmd.Stdout = &out
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		return nil, err
	}

	values := make(map[string]interface{})

	tmpFile := filepath.Join(os.TempDir(), fmt.Sprintf("defaults-%s.plist", strings.ReplaceAll(domain, ".", "-")))
	cmd = exec.Command("defaults", "export", domain, tmpFile)
	if err := cmd.Run(); err != nil {
		return nil, err
	}
	defer os.Remove(tmpFile)

	cmd = exec.Command("plutil", "-convert", "json", "-o", "-", tmpFile)
	var jsonOut bytes.Buffer
	cmd.Stdout = &jsonOut
	if err := cmd.Run(); err != nil {
		return nil, err
	}

	if err := json.Unmarshal(jsonOut.Bytes(), &values); err != nil {
		return nil, err
	}

	return values, nil
}

func (d *DefaultsManager) RestoreAll(backupFile string) error {
	data, err := os.ReadFile(backupFile)
	if err != nil {
		return fmt.Errorf("failed to read backup file: %w", err)
	}

	var domains []DefaultsDomain
	if err := json.Unmarshal(data, &domains); err != nil {
		return fmt.Errorf("failed to parse backup file: %w", err)
	}

	for _, domain := range domains {
		if err := d.restoreDomain(domain); err != nil {
			fmt.Printf("  ⚠️  Failed to restore %s: %v\n", domain.Domain, err)
			continue
		}
		fmt.Printf("  ✓ Restored %s\n", domain.Domain)
	}

	fmt.Println("\n⚠️  Note: Some changes require logout/restart to take effect")
	fmt.Println("   Consider running: killall Dock Finder SystemUIServer")

	return nil
}

func (d *DefaultsManager) restoreDomain(domain DefaultsDomain) error {

	tmpFile := filepath.Join(os.TempDir(), fmt.Sprintf("restore-%s.plist", strings.ReplaceAll(domain.Domain, ".", "-")))
	defer os.Remove(tmpFile)

	jsonData, err := json.Marshal(domain.Values)
	if err != nil {
		return err
	}

	if err := os.WriteFile(tmpFile, jsonData, 0644); err != nil {
		return err
	}

	cmd := exec.Command("plutil", "-convert", "xml1", tmpFile)
	if err := cmd.Run(); err != nil {
		return err
	}

	cmd = exec.Command("defaults", "import", domain.Domain, tmpFile)
	var stderr bytes.Buffer
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("%w: %s", err, stderr.String())
	}

	return nil
}

func (d *DefaultsManager) generateRestoreScript(domains []DefaultsDomain) string {
	var script strings.Builder

	script.WriteString("#!/bin/bash\n")
	script.WriteString("# macOS Defaults Restore Script\n")
	script.WriteString("# Generated by stash\n")
	script.WriteString("# Run this script to manually restore macOS settings\n\n")
	script.WriteString("set -e\n\n")
	script.WriteString("echo \"🔧 Restoring macOS defaults...\"\n\n")

	for _, domain := range domains {
		script.WriteString(fmt.Sprintf("# %s\n", domain.Domain))
		script.WriteString(fmt.Sprintf("defaults import %s macos-defaults.json 2>/dev/null || true\n\n", domain.Domain))
	}

	script.WriteString("echo \"✓ Defaults restored\"\n")
	script.WriteString("echo \"⚠️  Restarting affected services...\"\n")
	script.WriteString("killall Dock Finder SystemUIServer 2>/dev/null || true\n")
	script.WriteString("echo \"✓ Complete! Some changes may require logout/restart\"\n")

	return script.String()
}

func (d *DefaultsManager) GetStats(backupFile string) (int, error) {
	data, err := os.ReadFile(backupFile)
	if err != nil {
		return 0, err
	}

	var domains []DefaultsDomain
	if err := json.Unmarshal(data, &domains); err != nil {
		return 0, err
	}

	return len(domains), nil
}
